version: 2.1

orbs:
  python: circleci/python@1.5.0

workflows:
  run-tests:
    jobs:
      - test-3-7
      - test-3-8
      - test-3-9
      - test-3-10

jobs:
  test-3-7: &test-template
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run typecheck
          command: mypy -p pysubs2
  test-3-8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
  test-3-9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9
  test-3-10:
    <<: *test-template
    docker:
      - image: circleci/python:3.10

# Testing multiple Python versions inspired by: https://stackoverflow.com/a/60018883
